---
title: "TidyTemplate"
date: 2020-10-22
output: html_output
editor_options: 
  chunk_output_type: console
---

# TidyTuesday

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE, cache = TRUE,
                      warning = FALSE, message = FALSE,
                      dpi = 180, fig.height = 5, fig.width = 8)

library(tidyverse)
library(tidytuesdayR)
library(scales)
library(glue)

theme_set(theme_light())
```

# Load the weekly Data

Dowload the weekly data and make available in the `tt` object.

```{r Load}

tt <- tt_load("2020-10-20")
beer_awards <- tt$beer_awards %>% 
    mutate(state = str_to_upper(state),
           medal = fct_relevel(medal, c("Bronze", "Silver")))

```

```{r}
beer_counts <- beer_awards %>% 
    count(beer_name, brewery, medal, city, state)


```

```{r}
beer_counts %>% 
    pivot_wider(names_from = medal, values_from = n, values_fill = 0) %>% 
    mutate(total = Gold + Silver + Bronze) %>% 
    arrange(desc(total))
    
```

```{r}
beer_counts %>% 
    mutate(beer_name = glue("{beer_name}({brewery})")) %>% 
    filter(fct_lump(beer_name, 16, w = n) != "Other") %>% 
    mutate(beer_name = fct_reorder(beer_name, n, sum)) %>% 
    ggplot(aes(n, beer_name, fill = medal)) +
    geom_col()


```

```{r}
by_brewery <- beer_awards %>% 
    group_by(brewery) %>% 
    summarise(n_medal = n(),
              n_beer = n_distinct(beer_name),
              n_gold = sum(medal == "Gold"),
              weighted_medal = sum(as.numeric(medal))) %>% 
    arrange(desc(n_medal))
```

```{r}
beer_awards %>% 
    filter(fct_lump(state, 10) != "Other",
           fct_lump(category,10) != "Other") %>% 
    count(state, category)
```

```{r}
beer_df <- beer_awards %>% 
  group_by(beer_name) %>% 
  add_count(medal) %>% 
  rename("past_award" = n) %>% 
  ungroup()

```

Lets create a model for medal prediction

```{r}
library(tidymodels)
```

data split
```{r}
beer_split <- beer_df %>% 
  initial_split(strata = medal)

beer_train <- training(beer_split)
beer_test <- testing(beer_split)
```

recipe
```{r}
beer_recipe <- recipe(medal ~., data = beer_train) %>% 
  step_other(beer_name,
             brewery,
             city,
             state,
             category) %>% 
  step_dummy(all_nominal(), - all_outcomes())

beer_recipe %>% prep()
```

model spec
```{r}
rf_spec <- rand_forest() %>% 
  set_engine("ranger") %>% 
  set_mode("classification")

```

workflow
```{r}
beer_wf <- workflow() %>% 
  add_recipe(beer_recipe) %>% 
  add_model(rf_spec)
```

model fit
```{r}

beer_fit <- beer_wf %>% 
  fit(beer_train)

beer_res <- bind_cols(medal = beer_test$medal,
                      beer_fit %>%
                        predict(beer_test))
beer_res %>% 
  conf_mat(medal, .pred_class)
```

